/**
 * The versioned evidence of a Testnet validation (#18): a Markdown page for people and a JSON file with the full audit
 * reports, both under `docs/evidence/testnet/`. Pure: the CLI writes the files. Contains identifiers, links, timings
 * and audit verdicts only — never a key, a holder identifier or a URL beyond the public endpoints.
 */
import type { AuditSummary, RunEvidence, VerificationPlan, VerificationResult } from "./verification";
import { runIdOf } from "./verification";

/** Directory of the evidence, relative to the repository root. */
export const EVIDENCE_DIR = "docs/evidence/testnet";

export interface VerificationReport {
  schemaVersion: 1;
  kind: "testnet-credential-validation";
  runId: string;
  ok: boolean;
  plan: VerificationPlan;
  result: VerificationResult;
}

export function buildVerificationReport(plan: VerificationPlan, result: VerificationResult): VerificationReport {
  return {
    schemaVersion: 1,
    kind: "testnet-credential-validation",
    runId: runIdOf(Date.parse(result.startedAt)),
    ok: result.ok,
    plan,
    result,
  };
}

/** `docs/evidence/testnet/<runId>.md` and `.json`. */
export function reportPaths(report: Pick<VerificationReport, "runId">): { markdown: string; json: string } {
  const base = `${EVIDENCE_DIR}/${report.runId}`;
  return { markdown: `${base}.md`, json: `${base}.json` };
}

export function reportJson(report: VerificationReport): string {
  return `${JSON.stringify(report, (_key, v) => (typeof v === "bigint" ? v.toString() : v), 2)}\n`;
}

const link = (label: string, url: string | null | undefined) => (url ? `[${label}](${url})` : label);
const seconds = (ms: number | undefined) => (ms === undefined ? "—" : `${(ms / 1000).toFixed(1)} s`);
const code = (value: string) => `\`${value}\``;

function auditRows(label: string, audit: AuditSummary | undefined): string[] {
  if (!audit) return [`| ${label} | not reached | — | — | — |`];
  const findings = audit.findings.length ? audit.findings.map(f => `${f.code} (${f.severity})`).join(", ") : "none";
  return [
    `| ${label} | ${audit.ok ? "✅" : "❌"} ${code(audit.evidence)} | ${code(audit.onChainStatus)} | ${audit.attempts} in ${seconds(audit.elapsedMs)} | ${findings} |`,
  ];
}

function runSection(run: RunEvidence): string[] {
  const lines = [
    `### Run ${run.index} — ${run.ok ? "✅ passed" : "❌ failed"}`,
    "",
    `- Reference: ${code(run.reference)}`,
    `- Credential ID: ${run.credentialId ? code(run.credentialId) : "—"}`,
    "",
    "| Step | HCS evidence (consensus receipt first) | Registry transaction | Duration |",
    "|---|---|---|---|",
  ];
  for (const [label, step] of [
    ["Issuance", run.issuance],
    ["Revocation", run.revocation],
  ] as const) {
    if (!step) {
      lines.push(`| ${label} | not reached | not reached | — |`);
      continue;
    }
    lines.push(
      `| ${label} | ${link(`${code(step.hcs.transactionId)} (seq ${step.hcs.sequence})`, step.hcs.hashscanUrl)} · ${link("Mirror", step.hcs.mirrorMessageUrl)} | ${link(code(step.registry.transactionHash), step.registry.hashscanUrl)} · ${link("Mirror", step.registry.mirrorUrl)} | ${seconds(step.durationMs)} |`,
    );
  }
  lines.push(
    "",
    "Audit (`auditCredential`, Mirror Node ↔ `statusOf`):",
    "",
    "| When | Evidence | On-chain status | Attempts | Findings |",
    "|---|---|---|---|---|",
    ...auditRows("After issuance", run.auditAfterIssuance),
    ...auditRows("After revocation", run.auditAfterRevocation),
    "",
  );
  if (run.blockedAttempts.length) {
    lines.push("Deliberate replays (must be refused, with nothing published or paid):", "");
    lines.push("| Attempt | Refused with | Nothing paid |", "|---|---|---|");
    for (const a of run.blockedAttempts) {
      lines.push(
        `| ${a.description} | ${a.blocked ? "✅" : "❌"} ${a.code ? code(a.code) : "not refused"} | ${a.nothingPaid ? "✅" : "❌"} |`,
      );
    }
    lines.push("");
  }
  const timeline = run.auditAfterRevocation?.timeline ?? run.auditAfterIssuance?.timeline ?? [];
  if (timeline.length) {
    lines.push("Timeline (consensus order, from the audit):", "");
    for (const t of timeline)
      lines.push(`1. ${code(t.step)} at ${code(t.consensusTimestamp)} — ${link(t.reference, t.hashscanUrl)}`);
    lines.push("");
  }
  if (run.failure) {
    lines.push(
      `**Failed at ${run.failure.stage}:** [${run.failure.error.code}] ${run.failure.error.message}`,
      ...(run.failure.error.transactionId ? [`HCS transaction: ${code(run.failure.error.transactionId)}`] : []),
      ...(run.failure.error.transactionHash
        ? [`Registry transaction: ${code(run.failure.error.transactionHash)}`]
        : []),
      "",
    );
  }
  return lines;
}

export function renderReportMarkdown(report: VerificationReport): string {
  const { plan, result } = report;
  const lines = [
    `# Testnet validation ${report.runId} — ${report.ok ? "✅ passed" : "❌ failed"}`,
    "",
    "Generated by `yarn verify:testnet` (issue #18). Evidence of a real run on Hedera Testnet: the credential is",
    "published to HCS and its consensus receipt captured before the `CredentialRegistry` transaction (ADR D11), then",
    "audited through the Mirror Node with the shared audit. HCS is evidence; `statusOf` is the authority.",
    `Full audit reports: [${report.runId}.json](${report.runId}.json).`,
    "",
    "## Setup",
    "",
    `- Network: ${plan.network} (chain ${plan.chainId})`,
    `- Operator: ${plan.operatorId}`,
    `- CredentialRegistry: ${link(code(plan.registry.address), plan.registry.hashscanUrl)} (${plan.registry.source === "manifest" ? "packages/sdk/generated" : "HEDERA_CREDENTIAL_REGISTRY_ADDRESS"})`,
    `- HCS topic: ${link(code(plan.topic.id), plan.topic.hashscanUrl)}`,
    `- Issuer namespace: ${code(plan.issuer.name)} (${code(plan.issuer.id)}), signer ${code(plan.issuer.signer)}`,
    `- Started ${result.startedAt}, finished ${result.finishedAt} (${seconds(result.durationMs)})`,
    `- Estimated cost: ${plan.cost.totalHbar ? `≤ ${plan.cost.totalHbar} HBAR (about $${plan.cost.totalUsd})` : "unknown"}`,
    "",
  ];
  if (result.registration) {
    lines.push(
      `Issuer namespace registered in this run: ${link(code(result.registration.transactionHash), result.registration.hashscanUrl)} (${seconds(result.registration.durationMs)}).`,
      "",
    );
  }
  if (result.registrationFailure) {
    lines.push(
      `**Issuer registration failed:** [${result.registrationFailure.code}] ${result.registrationFailure.message}`,
      "",
    );
  }
  lines.push(`## Runs (${result.runs.length} of ${plan.runs})`, "");
  for (const run of result.runs) lines.push(...runSection(run));
  return `${lines.join("\n").trimEnd()}\n`;
}
