import { expect } from "chai";
import hre from "hardhat";
import { deployments as committedDeployments } from "@sh/sdk/generated";
import {
  abiHash,
  collectArtifacts,
  renderGeneratedFiles,
  staleFiles,
  toDeploymentEntries,
} from "../scripts/generateTsAbis";
import type { ContractArtifact, DeploymentEntry, DeploymentManifest } from "../scripts/generateTsAbis";

const ABI_A = [
  { type: "function", name: "ping", inputs: [], outputs: [{ type: "uint256", name: "" }], stateMutability: "view" },
  { type: "error", name: "Nope", inputs: [{ type: "bytes32", name: "key" }] },
];
const ABI_B = [{ type: "error", name: "Nope", inputs: [{ type: "bytes32", name: "key" }] }];

const entry = (address: string, abi: readonly unknown[]): DeploymentEntry => ({
  address,
  contractId: "0.0.1234",
  deployTxHash: `0x${"ab".repeat(32)}`,
  blockNumber: 7,
  abiHash: abiHash(abi),
});

describe("ABI/address codegen (#24)", function () {
  it("committed packages/sdk/generated matches the compiled contracts (run `yarn codegen` if this fails)", async function () {
    const { files } = renderGeneratedFiles({
      artifacts: await collectArtifacts(hre),
      existing: committedDeployments as DeploymentManifest,
    });
    expect(staleFiles(files)).to.deep.equal([]);
  });

  it("is deterministic regardless of input order", function () {
    const a: ContractArtifact = { name: "Alpha", abi: ABI_A };
    const b: ContractArtifact = { name: "Beta", abi: ABI_B };
    const existing: DeploymentManifest = { local: { Beta: entry("0x" + "2".repeat(40), ABI_B) } };
    const one = renderGeneratedFiles({ artifacts: [a, b], existing });
    const two = renderGeneratedFiles({ artifacts: [b, a], existing });
    expect(one.files).to.deep.equal(two.files);
    expect(one.files["abis.ts"]).to.match(/^\/\/ Autogenerated .* Do not edit\./);
  });

  it("replaces only the deployed network and keeps every other one", function () {
    const artifacts = [{ name: "Alpha", abi: ABI_A }];
    const existing: DeploymentManifest = {
      local: { Alpha: entry("0x" + "1".repeat(40), ABI_A) },
      testnet: { Alpha: entry("0x" + "2".repeat(40), ABI_A) },
    };
    const { files } = renderGeneratedFiles({
      artifacts,
      existing,
      update: { network: "testnet", contracts: { Alpha: entry("0x" + "3".repeat(40), ABI_A) } },
    });
    expect(files["deployments.ts"]).to.contain("1".repeat(40));
    expect(files["deployments.ts"]).to.contain("3".repeat(40));
    expect(files["deployments.ts"]).not.to.contain("2".repeat(40));
  });

  it("drops deployments of contracts that no longer exist, with a warning", function () {
    const { files, warnings } = renderGeneratedFiles({
      artifacts: [{ name: "Alpha", abi: ABI_A }],
      existing: { testnet: { Gone: entry("0x" + "4".repeat(40), ABI_B) } },
    });
    expect(files["deployments.ts"]).not.to.contain("Gone");
    expect(warnings).to.deep.equal([
      "Dropped the testnet deployment of Gone: no such contract under contracts/ any more.",
    ]);
  });

  it("merges a custom error declared by several contracts into one selector entry", function () {
    const { files } = renderGeneratedFiles({
      artifacts: [
        { name: "Alpha", abi: ABI_A },
        { name: "Beta", abi: ABI_B },
      ],
      existing: {},
    });
    expect(files["errors.ts"].match(/"name": "Nope"/g)).to.have.length(1);
    expect(files["errors.ts"]).to.contain('"Alpha",\n      "Beta"');
  });

  it("rejects duplicate contract names", function () {
    expect(() =>
      renderGeneratedFiles({
        artifacts: [
          { name: "Alpha", abi: ABI_A },
          { name: "Alpha", abi: ABI_B },
        ],
        existing: {},
      }),
    ).to.throw("Two contracts are named Alpha");
  });

  it("puts the address and ABI of a real deployment in the manifest without manual edits", async function () {
    await hre.deployments.fixture(["CredentialRegistry"]);
    const artifacts = await collectArtifacts(hre);
    const { contracts } = await toDeploymentEntries(
      await hre.deployments.all(),
      new Set(artifacts.map(a => a.name)),
      async () => "0.0.4242",
    );
    const deployed = await hre.deployments.get("CredentialRegistry");
    expect(contracts.CredentialRegistry).to.include({
      address: deployed.address.toLowerCase(),
      contractId: "0.0.4242",
      abiHash: abiHash(artifacts.find(a => a.name === "CredentialRegistry")!.abi),
    });

    const { files } = renderGeneratedFiles({
      artifacts,
      existing: {},
      update: { network: "testnet", contracts },
    });
    expect(files["deployments.ts"]).to.contain(`"address": "${deployed.address.toLowerCase()}"`);
    expect(files["abis.ts"]).to.contain("export const CredentialRegistryAbi = [");
  });
});
