/**
 * ABI/address codegen (#24): Solidity → compile → artifacts → `packages/sdk/generated/` → SDK resolver → hooks → UI.
 *
 * Runs at the end of every `hardhat deploy` (task override in hardhat.config.ts) and as `yarn codegen`. It writes:
 * - `abis.ts`: the ABI of every deployable contract under `contracts/`, `as const` for typed consumers;
 * - `deployments.ts`: the deployment manifest keyed by Hedera network name (chain ids stay in `networks.ts`). A deploy
 *   replaces the entry of ITS network only; every other network is kept as committed;
 * - `errors.ts`: selector → custom error, for decoding reverts without a hand-maintained table;
 * - `index.ts`.
 *
 * `renderGeneratedFiles` is pure and deterministic (same input → byte-identical output), which is what the drift test
 * and `yarn codegen --check` rely on. Only `runCodegen` touches the file system, the chain and the Mirror Node.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { Interface, keccak256, toUtf8Bytes } from "ethers";
import type { InterfaceAbi } from "ethers";
import { HardhatPluginError } from "hardhat/plugins";
import type { HardhatRuntimeEnvironment } from "hardhat/types";
import type { Deployment } from "hardhat-deploy/types";
import { getNetwork, hashscanContractUrl, lookupContractId, networkNameByChainId } from "@sh/sdk";
import type { HederaNetwork, HederaNetworkName } from "@sh/sdk";
import { deployments as committedDeployments } from "@sh/sdk/generated";

export const GENERATED_DIR = path.resolve(__dirname, "../../sdk/generated");

const HEADER =
  "// Autogenerated by packages/hardhat/scripts/generateTsAbis.ts (`yarn codegen`, `yarn deploy`). Do not edit.\n";

export interface ContractArtifact {
  name: string;
  abi: readonly unknown[];
}

export interface DeploymentEntry {
  address: string;
  contractId: string | null;
  deployTxHash: string | null;
  blockNumber: number | null;
  abiHash: string;
}

export type DeploymentManifest = Partial<Record<HederaNetworkName, Partial<Record<string, DeploymentEntry>>>>;

export interface CodegenInput {
  artifacts: ContractArtifact[];
  /** The manifest as committed. */
  existing: DeploymentManifest;
  /** The deployments of the network that was just deployed to; replaces that network's entry. */
  update?: { network: HederaNetworkName; contracts: Record<string, DeploymentEntry> } | null;
}

export interface CodegenOutput {
  /** File name (inside `packages/sdk/generated`) → content. */
  files: Record<string, string>;
  warnings: string[];
}

/** Fingerprint of an ABI: keccak256 of its sorted human-readable signatures, insensitive to JSON layout. */
export function abiHash(abi: readonly unknown[]): string {
  const signatures = new Interface(abi as InterfaceAbi).format(false).slice().sort();
  return keccak256(toUtf8Bytes(signatures.join("\n")));
}

const byKey = <T>(record: Partial<Record<string, T>>) =>
  Object.keys(record)
    .sort()
    .map(key => [key, record[key] as T] as const);

const json = (value: unknown) => JSON.stringify(value, null, 2);

function renderAbis(artifacts: ContractArtifact[]): string {
  const consts = artifacts.map(a => `export const ${a.name}Abi = ${json(a.abi)} as const;\n`);
  const map = artifacts.length ? `{\n${artifacts.map(a => `  ${a.name}: ${a.name}Abi,\n`).join("")}}` : "{}";
  return [
    HEADER,
    ...consts,
    `export const contractAbis = ${map} as const;\n`,
    "export type ContractName = keyof typeof contractAbis;\n",
  ].join("\n");
}

function renderDeployments(manifest: DeploymentManifest): string {
  const ordered: Record<string, Record<string, DeploymentEntry>> = {};
  for (const [network, contracts] of byKey(manifest)) {
    const entries = byKey(contracts ?? {});
    if (entries.length === 0) continue;
    ordered[network] = Object.fromEntries(
      entries.map(([name, d]) => [
        name,
        {
          address: d.address,
          contractId: d.contractId,
          deployTxHash: d.deployTxHash,
          blockNumber: d.blockNumber,
          abiHash: d.abiHash,
        },
      ]),
    );
  }
  return [
    HEADER,
    'import type { HederaNetworkName } from "../hedera/networks";',
    'import type { ContractName } from "./abis";\n',
    "export const DEPLOYMENTS_SCHEMA_VERSION = 1;\n",
    "export interface DeploymentRecord {",
    "  /** Lowercase EVM address. */",
    "  address: `0x${string}`;",
    "  /** Hedera contract id (`0.0.x`) from the Mirror Node; `null` if it had not indexed the contract yet. */",
    "  contractId: string | null;",
    "  deployTxHash: `0x${string}` | null;",
    "  blockNumber: number | null;",
    "  /** `abiHash` of the ABI that was deployed; differs from the current ABI after a contract change. */",
    "  abiHash: `0x${string}`;",
    "}\n",
    "export type GeneratedDeployments = Partial<Record<HederaNetworkName, Partial<Record<ContractName, DeploymentRecord>>>>;\n",
    `export const deployments: GeneratedDeployments = ${json(ordered)};\n`,
  ].join("\n");
}

function renderErrors(artifacts: ContractArtifact[]): string {
  const table = new Map<string, { name: string; signature: string; contracts: string[] }>();
  for (const artifact of artifacts) {
    new Interface(artifact.abi as InterfaceAbi).forEachError(fragment => {
      const entry = table.get(fragment.selector) ?? {
        name: fragment.name,
        signature: fragment.format("sighash"),
        contracts: [],
      };
      if (!entry.contracts.includes(artifact.name)) entry.contracts.push(artifact.name);
      table.set(fragment.selector, entry);
    });
  }
  const ordered = Object.fromEntries(
    [...table.keys()].sort().map(selector => {
      const e = table.get(selector)!;
      return [selector, { name: e.name, signature: e.signature, contracts: e.contracts.sort() }];
    }),
  );
  return [
    HEADER,
    'import type { ContractName } from "./abis";\n',
    "export interface ContractErrorEntry {",
    "  name: string;",
    "  /** Canonical signature, e.g. `AlreadyIssued(bytes32)`. */",
    "  signature: string;",
    "  contracts: readonly ContractName[];",
    "}\n",
    "/** Custom error selector → error, across every contract of the template (inherited errors included). */",
    `export const contractErrors: Record<string, ContractErrorEntry> = ${json(ordered)};\n`,
  ].join("\n");
}

const INDEX = `${HEADER}\nexport * from "./abis";\nexport * from "./deployments";\nexport * from "./errors";\n`;

export function renderGeneratedFiles(input: CodegenInput): CodegenOutput {
  const warnings: string[] = [];
  const artifacts = [...input.artifacts].sort((a, b) => a.name.localeCompare(b.name));
  const names = new Set<string>();
  for (const a of artifacts) {
    if (names.has(a.name)) throw new Error(`Two contracts are named ${a.name}; contract names must be unique.`);
    if (!/^[A-Za-z_$][\w$]*$/.test(a.name)) throw new Error(`${a.name} is not a valid identifier.`);
    names.add(a.name);
  }

  const manifest: DeploymentManifest = { ...input.existing };
  if (input.update) manifest[input.update.network] = input.update.contracts;

  // A manifest entry for a contract that no longer exists would not type-check against ContractName.
  for (const [network, contracts] of byKey(manifest)) {
    for (const [name] of byKey(contracts ?? {})) {
      if (!names.has(name)) {
        warnings.push(`Dropped the ${network} deployment of ${name}: no such contract under contracts/ any more.`);
        delete contracts![name];
      }
    }
  }

  return {
    files: {
      "abis.ts": renderAbis(artifacts),
      "deployments.ts": renderDeployments(manifest),
      "errors.ts": renderErrors(artifacts),
      "index.ts": INDEX,
    },
    warnings,
  };
}

/** Deployable contracts compiled from `contracts/` (interfaces, abstract contracts and dependencies are skipped). */
export async function collectArtifacts(hre: HardhatRuntimeEnvironment): Promise<ContractArtifact[]> {
  const names = (await hre.artifacts.getAllFullyQualifiedNames()).filter(n => n.startsWith("contracts/"));
  const artifacts: ContractArtifact[] = [];
  for (const name of names) {
    const artifact = await hre.artifacts.readArtifact(name);
    if (!artifact.bytecode || artifact.bytecode === "0x") continue;
    artifacts.push({ name: artifact.contractName, abi: artifact.abi });
  }
  return artifacts;
}

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/** The Mirror Node indexes a new contract a few seconds after consensus: retry within a small budget. */
async function resolveContractId(network: HederaNetwork, address: string, attempts = 6, delayMs = 2_500) {
  for (let i = 0; i < attempts; i++) {
    const id = await lookupContractId(network, address);
    if (id) return id;
    if (i < attempts - 1) await sleep(delayMs);
  }
  return null;
}

/**
 * The deployments hardhat-deploy recorded for the current network. `null` (keep the committed manifest) on the
 * in-process Hardhat network, on a chain that is not a Hedera network, or when this checkout has no deployment files.
 */
async function collectDeployments(
  hre: HardhatRuntimeEnvironment,
  contractNames: Set<string>,
): Promise<{ update: CodegenInput["update"]; network: HederaNetwork | null; notes: string[] }> {
  const notes: string[] = [];
  if (!hre.network.live) {
    notes.push(`${hre.network.name} is not a live network: deployments are not recorded, ABIs only.`);
    return { update: null, network: null, notes };
  }
  const chainId = await hre.getChainId();
  const name = networkNameByChainId(Number(chainId));
  if (!name) {
    notes.push(`Chain ${chainId} is not a Hedera network of networks.ts: deployments are not recorded.`);
    return { update: null, network: null, notes };
  }
  const all = await hre.deployments.all();
  if (Object.keys(all).length === 0) {
    notes.push(`No deployment files for ${hre.network.name} in this checkout: the committed ${name} entry is kept.`);
    return { update: null, network: null, notes };
  }

  const network = getNetwork(name, process.env);
  const { contracts, notes: entryNotes } = await toDeploymentEntries(all, contractNames, address =>
    resolveContractId(network, address),
  );
  for (const contract of Object.keys(contracts).filter(c => !contracts[c].contractId)) {
    notes.push(
      `The Mirror Node has not indexed ${contract} yet; run \`yarn codegen --network ${hre.network.name}\` later.`,
    );
  }
  return { update: { network: name, contracts }, network, notes: [...notes, ...entryNotes] };
}

/** Converts hardhat-deploy records into manifest entries; deployments of contracts outside `contracts/` are skipped. */
export async function toDeploymentEntries(
  all: Record<string, Deployment>,
  contractNames: Set<string>,
  resolveId: (address: string) => Promise<string | null>,
): Promise<{ contracts: Record<string, DeploymentEntry>; notes: string[] }> {
  const notes: string[] = [];
  const contracts: Record<string, DeploymentEntry> = {};
  for (const [contract, d] of Object.entries(all).sort(([a], [b]) => a.localeCompare(b))) {
    if (!contractNames.has(contract)) {
      notes.push(`Skipped deployment ${contract}: not a contract under contracts/.`);
      continue;
    }
    const address = d.address.toLowerCase();
    contracts[contract] = {
      address,
      contractId: await resolveId(address),
      deployTxHash: d.transactionHash?.toLowerCase() ?? null,
      blockNumber: d.receipt?.blockNumber ?? null,
      abiHash: abiHash(d.abi),
    };
  }
  return { contracts, notes };
}

/** Files whose content on disk differs from `files` (missing files included). */
export function staleFiles(files: Record<string, string>, dir = GENERATED_DIR): string[] {
  return Object.keys(files).filter(file => {
    const target = path.join(dir, file);
    return !existsSync(target) || readFileSync(target, "utf8") !== files[file];
  });
}

export async function runCodegen(hre: HardhatRuntimeEnvironment, options: { check?: boolean } = {}): Promise<void> {
  const artifacts = await collectArtifacts(hre);
  const names = new Set(artifacts.map(a => a.name));
  const collected = options.check ? { update: null, network: null, notes: [] } : await collectDeployments(hre, names);
  const { files, warnings } = renderGeneratedFiles({
    artifacts,
    existing: committedDeployments as DeploymentManifest,
    update: collected.update,
  });
  for (const line of [...collected.notes, ...warnings]) console.log(`codegen: ${line}`);

  const stale = staleFiles(files);
  if (options.check) {
    if (stale.length > 0) {
      throw new HardhatPluginError(
        "codegen",
        `packages/sdk/generated is stale (${stale.join(", ")}). Run \`yarn codegen\` and commit the result.`,
      );
    }
    console.log("codegen: packages/sdk/generated is up to date.");
    return;
  }

  mkdirSync(GENERATED_DIR, { recursive: true });
  for (const file of stale) writeFileSync(path.join(GENERATED_DIR, file), files[file]);
  console.log(
    stale.length
      ? `codegen: wrote ${stale.join(", ")} in packages/sdk/generated.`
      : "codegen: packages/sdk/generated already up to date.",
  );

  if (collected.update && collected.network) {
    for (const [name, d] of Object.entries(collected.update.contracts)) {
      const url = hashscanContractUrl(collected.network, d.contractId ?? d.address);
      console.log(
        `codegen: ${name} on ${collected.update.network}: ${d.address}${d.contractId ? ` (${d.contractId})` : ""}`,
      );
      if (url) console.log(`codegen:   ${url}`);
    }
  }
}
